// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );

        
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCgkR_pVYpGbMkwoCxT84Qrf2liDctex8',
    appId: '1:609664181004:web:6942bbcffd8867a85edf29',
    messagingSenderId: '609664181004',
    projectId: 'slushies-7eaf7',
    authDomain: 'slushies-7eaf7.firebaseapp.com',
    storageBucket: 'slushies-7eaf7.firebasestorage.app',
    measurementId: 'G-KJF4J0BM0N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCgkR_pVYpGbMkwoCxT84Qrf2liDctex8',
    appId: '1:609664181004:web:6942bbcffd8867a85edf29',
    messagingSenderId: '609664181004',
    projectId: 'slushies-7eaf7',
    authDomain: 'slushies-7eaf7.firebaseapp.com',
    storageBucket: 'slushies-7eaf7.firebasestorage.app',
    measurementId: 'G-KJF4J0BM0N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZ0eI_w6tLfcP3HDn8yXxOnibMJRYwsk',
    appId: '1:609664181004:ios:a1d9e36bb3e0e89c5edf29',
    messagingSenderId: '609664181004',
    projectId: 'slushies-7eaf7',
    storageBucket: 'slushies-7eaf7.firebasestorage.app',
    iosBundleId: 'com.example.slushies',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZ0eI_w6tLfcP3HDn8yXxOnibMJRYwsk',
    appId: '1:609664181004:ios:a1d9e36bb3e0e89c5edf29',
    messagingSenderId: '609664181004',
    projectId: 'slushies-7eaf7',
    storageBucket: 'slushies-7eaf7.firebasestorage.app',
    iosBundleId: 'com.example.slushies',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWiZiBcyUiE799UH9eTEOKdxzZAhIMrc',
    appId: '1:609664181004:android:afe274edeeea91925edf29',
    messagingSenderId: '609664181004',
    projectId: 'slushies-7eaf7',
    storageBucket: 'slushies-7eaf7.firebasestorage.app',
  );

}